### ISSUE TITLE
Feature: custom issue title

### ISSUE THREAD

**Issue by hazcod** [zaproxy/action-baseline#10]
Would be very nice to be able to specify the issue title via a GitHub Action argument.

**Comment by sshniro** [comment]
Thank you, yes this should be an easy fix, would you like to contribute to this feature @hazcod ?

**Comment by hazcod** [comment]
I'll fix that today for you @sshniro and open a PR.

**Comment by hazcod** [comment]
Fixed by https://github.com/zaproxy/action-baseline/pull/13
