### ISSUE TITLE
Permission issue while Ajax scanning with root user

### ISSUE THREAD

**Issue by sshniro** [zaproxy/action-baseline#33]
![image](https://user-images.githubusercontent.com/13045528/82639136-6cf6b380-9c08-11ea-8284-63b4053fbb8f.png)

**Comment by sshniro** [comment]
Seems like this is a prominent problem. @thc202 @psiinon I think in order to fix this we need to create a dedicated docker for action scan and in that docker file we should not use ZAP user.

Because the reason for this problem is Github action cannot persist file if a docker uses any user other than root. So shall I create another docker file for action? wdyt

**Comment by psiinon** [comment]
I've found a workaround which we use in the ZAP test scans.
We create the files we know are required using the root user and give write access to everyone, then we run ZAP using the zap user.
Example: https://github.com/zapbot/zap-mgmt-scripts/blob/master/.github/workflows/zap-vs-ssti.yml#L42-L46
I think this workaround will work here too...
