### ISSUE TITLE
Capturing the ZAP scan run results and publish into Slack

### ISSUE THREAD

**Issue by chenrui333** [zaproxy/action-baseline#40]
Hi 👋 

I have a use case to capture the action run result and publish it into slack, not sure if anyone has done that. Thanks!

**Comment by kingthorin** [comment]
Please don't ask questions as issues, especially when providing zero details - the [ZAP User Group]( https://groups.google.com/group/zaproxy-users) is a much better place for questions.

If you’re asking about a third party components such as the Jenkins plugin or VSTS plugin please look for their preferred support mechanism as these were not created by and are not supported by the core team.

It should be possible to get the necessary information from ZAP’s API and send it to Slack via whatever “normal” library you wish.

**Comment by chenrui333** [comment]
Sounds good, I will redirect this to there then. Thanks!
