### ISSUE TITLE
`Cannot listen on port 0.0.0.0:60926` error

### ISSUE THREAD

**Issue by chenrui333** [zaproxy/action-baseline#52]
First time seeing this error in the github action run.

```
10217 [ZAP-DownloadInstaller] ERROR org.zaproxy.zap.control.AddOnInstaller - An error occurred while installing the add-on: websocket
java.security.InvalidParameterException: ScriptType already registered: websocketfuzzerprocessor
...

11741 [ZAP-daemon] ERROR org.parosproxy.paros.core.proxy.ProxyServer - Cannot listen on port 0.0.0.0:60926 - try specifying a different port for ZAP to use
Cannot listen on port 0.0.0.0:60926 - try specifying a different port for ZAP to use
```

**Comment by kingthorin** [comment]
Could you link the run or provide further details?

**Comment by chenrui333** [comment]
After the quick rerun, the build is green now, so I think it might be simply a flaky run?

**Comment by kingthorin** [comment]
The port is selected randomly so it could just be unfortunate timing.

I was just curious about network access, addon use etc. to know if there was informational logs that might have pointed more specifically to what happened. No big deal.

**Comment by thc202** [comment]
Closing per previous comments.
